.PHONY: all clean

# provide all defines to recursive make calls
export

MAKEFLAGS = -r

BASEDIR=$(CURDIR)
SRCDIR=$(BASEDIR)/../src

CXX     = g++
CC      = gcc
AR      = ar
RANLIB  = ranlib

CP = cp
MV = mv

ASN1CDIR = /usr/local
ASN1C    = $(ASN1CDIR)/bin/asn1c
ASN1CINC = $(ASN1CDIR)/share/asn1c

LDFLAGS     = -shared
ARFLAGS     = -rvu
