.TH "_nmeaParserNODE" 3 "18 Jun 2010" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nmeaParserNODE \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpackType\fP"
.br
.ti -1c
.RI "void * \fBpack\fP"
.br
.ti -1c
.RI "\fB_nmeaParserNODE\fP * \fBnext_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file parser.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
