.TH "_nmeaGENERATOR" 3 "18 Jun 2010" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nmeaGENERATOR \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBgen_data\fP"
.br
.ti -1c
.RI "nmeaNMEA_GEN_INIT \fBinit_call\fP"
.br
.ti -1c
.RI "nmeaNMEA_GEN_LOOP \fBloop_call\fP"
.br
.ti -1c
.RI "nmeaNMEA_GEN_RESET \fBreset_call\fP"
.br
.ti -1c
.RI "nmeaNMEA_GEN_DESTROY \fBdestroy_call\fP"
.br
.ti -1c
.RI "\fB_nmeaGENERATOR\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file generator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
