.TH "_nmeaPARSER" 3 "18 Jun 2010" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nmeaPARSER \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBtop_node\fP"
.br
.ti -1c
.RI "void * \fBend_node\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBbuff_size\fP"
.br
.ti -1c
.RI "int \fBbuff_use\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file parser.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
