
#ifndef SOFTICONCUST_H
#define SOFTICONCUST_H 
#include "sysdefs.h"
#include "restypedefines.h"

/**In different system state,the indicators may be different.**/
typedef enum
{
  NUMBER_ENTRY_STATE,
  MEMORY_BROWSING_STATE,
  MEMORY_BROWSING_POPUP,
  MENU_STATE,
  QUERY_STATE,
  MESSAGE_EDITOR_STATE,
  CALENDAR_STATE,
  DEFAULT_STATE,
  DATE_TIME_SETTING_QUERY_STATE,
  NOTE_STATE,
  LEVEL_CONTROL_STATE,
  POWER_SAVER_MODE_STATE,
  TEXT_VIEWER_STATE
}SysStateIdT;

/**Every element has many indicator states.**/
typedef enum
{
  STATE_INVALID = -1,

  STATE_MESSAGE_WAITING,  //Not support in denali.
  STATE_NO_MESSAGE_WAITING,             /*blank */
  
  STATE_MESSAGE_SENDING,
  STATE_NO_MESSAGE_SENDING,             /*blank */
  
  STATE_MESSAGE_GENERAL,
  STATE_NO_MESSAGE_GENERAL,             /*blank */
  
  STATE_MESSAGE_VOICE,
  STATE_NO_MESSAGE_VOICE,             /*blank */

  STATE_MESSAGE_EMAIL,
  STATE_NO_MESSAGE_EMAIL,             /*blank */
  
  STATE_MESSAGE_FULL,
  STATE_NO_MESSAGE_FULL,             /*blank */
  
  /*Not support in denali.*/
  STATE_CHANNEL_TRAFFIC,
  STATE_CHANNEL_NOSERVICE,
  STATE_CHANNEL_BLANK,                 /*blank    */

  STATE_LEFTUPRSSI_LEVEL_0,
  STATE_LEFTUPRSSI_LEVEL_1,
  STATE_LEFTUPRSSI_LEVEL_2,
  STATE_LEFTUPRSSI_LEVEL_3,
  STATE_LEFTUPRSSI_LEVEL_4,
  STATE_LEFTUPRSSI_BLANK,                    /*blank */

  STATE_LONGRSSI_LEVEL_0,
  STATE_LONGRSSI_LEVEL_1,
  STATE_LONGRSSI_LEVEL_2,
  STATE_LONGRSSI_LEVEL_3,
  STATE_LONGRSSI_LEVEL_4,
  STATE_LONGRSSI_LEVEL_5,
  STATE_LONGRSSI_LEVEL_6,
  STATE_LONGRSSI_LEVEL_7,
  STATE_LONGRSSI_BLANK,                    /*blank */

  STATE_ROAM_YES,
  STATE_ROAM_BLINK_YES,
  STATE_ROAM_BLINK_NO,
  STATE_ROAM_NO,                     /*blank */

  //Not  support in denali.
  STATE_SIGNALMODE_DIGITAL,
  STATE_SIGNALMODE_ANOLOG,
  STATE_SIGNALMODE_1X,    
  STATE_SIGNALMODE_BLANK,              /*blank */

  /*Not support in denali.*/
  STATE_THREEGSTATE_ACTIVE,
  STATE_THREEGSTATE_SENDINGBLINK,
  STATE_THREEGSTATE_RECEIVINGBLINK,
  STATE_THREEGSTATE_DORMANT,
  STATE_THREEGSTATE_NO3G,
  STATE_THREEGSTATE_DISCONNECT,       /*blank */

  STATE_ALARM_ON,
  STATE_ALARM_OFF,                     /*blank */

  STATE_AIRPLANE_MODE_ON,
  STATE_AIRPLANE_MODE_OFF,   /*blank*/

  /*Not support in denali.*/
  STATE_ENVIRONMENT_GENERAL,
  STATE_ENVIRONMENT_SILENT,
  STATE_ENVIRONMENT_MEETING,
  STATE_ENVIRONMENT_OUTDOOR,
  STATE_ENVIRONMENT_USER_STYLE_1,
  STATE_ENVIRONMENT_USER_STYLE_2,
  STATE_ENVIRONMENT_BLANK,
  STATE_ENVIRONMENT_VIBRATE,

  STATE_BATTERY_LEVEL_OUTLINED,
  STATE_BATTERY_LEVEL_1,
  STATE_BATTERY_LEVEL_2,
  STATE_BATTERY_LEVEL_3,
  STATE_BATTERY_LEVEL_4,
  STATE_BATTERY_LEVEL_5,
  STATE_BATTERY_LEVEL_6,
  STATE_BATTERY_LEVEL_7,
  STATE_BATTERY_LEVEL_8,
  STATE_BATTERY_CHARGING_NOW,
  STATE_BATTERY_CHARGING_COMPLETE,
  STATE_BATTERY_NO_CHARGER,
  STATE_BATTERY_NO_BATTERY,
  STATE_BATTERY_UNKNOWN_BATTERY,

  STATE_HEADSET_CONNECT,
  STATE_HEADSET_DISCONNECT,

  STATE_USB_CABLE_INSERT,
  STATE_USB_CABLE_REMOVE,
  
  STATE_INCALL_YES,
  STATE_INCALL_NO,

  STATE_KEYGUARD_ON,
  STATE_KEYGUARD_OFF,

  STATE_SILENT_ON,
  STATE_SILENT_OFF,

  STATE_NETMON_3101,
  STATE_NETMON_3102,
  STATE_NETMON_3103,
  STATE_NETMON_3104,
  STATE_NETMON_3105,
  STATE_NETMON_3106,
  STATE_NETMON_3108,
  STATE_NETMON_3201,
  STATE_NETMON_3302,
  STATE_NETMON_3303,
  STATE_NETMON_3304,
  STATE_NETMON_3306,
  STATE_NETMON_3601,
  STATE_NETMON_3602,
  STATE_NETMON_3606,
  STATE_NETMON_3610,
  STATE_NETMON_3618,
  STATE_NETMON_3623,
  STATE_NETMON_6201,
  STATE_NETMON_7578,
  STATE_NETMON_BLANK,

  STATE_IHF_YES,
  STATE_IHF_NO,

  STATE_STOPWATCH_RUNNING,
  STATE_STOPWATCH_STOP,

  STATE_VIBRA_ON,
  STATE_VIBRA_OFF
}AnnStateIdT;

#define   STATE_MESSAGE_SM  STATE_MESSAGE_GENERAL

#define  STATE_RSSI_LEVEL_0      STATE_LONGRSSI_LEVEL_0
#define  STATE_RSSI_LEVEL_1      STATE_LONGRSSI_LEVEL_1
#define  STATE_RSSI_LEVEL_2      STATE_LONGRSSI_LEVEL_2
#define  STATE_RSSI_LEVEL_3      STATE_LONGRSSI_LEVEL_3
#define  STATE_RSSI_LEVEL_4      STATE_LONGRSSI_LEVEL_4
#define  STATE_RSSI_BLANK        STATE_LONGRSSI_BLANK

/**For every system state,there are many elements.**/
typedef enum
{
  ANN_ELEMENT_INVALID = -1,
  ANN_ELEMENT_MESSAGE_GENERAL,
  ANN_ELEMENT_MESSAGE_VOICE,
  ANN_ELEMENT_MESSAGE_SENDING,
  ANN_ELEMENT_MESSAGE_EMAIL,
  ANN_ELEMENT_MESSAGE_FULL,
  ANN_ELEMENT_CHANNEL,  //Not support in denali.
  ANN_ELEMENT_LEFTUPRSSI,
  ANN_ELEMENT_LONGRSSI,
  ANN_ELEMENT_ROAM,
  ANN_ELEMENT_SIGNALMODE,
  ANN_ELEMENT_3GSTATE,  //Not support in denali.
  ANN_ELEMENT_ALARM,
  ANN_ELEMENT_AIRPLANE_MODE,
  ANN_ELEMENT_ENVIRONMENT,  //Not support in denali.
  ANN_ELEMENT_BATTERY,
  ANN_ELEMENT_HEADSET,
  ANN_ELEMENT_USB_CABLE,

  ANN_ELEMENT_INCALL,
  ANN_ELEMENT_KEYGUARD,
  ANN_ELEMENT_SILENT,
  ANN_ELEMENT_NETMON,
  ANN_ELEMENT_IHF,
  ANN_ELEMENT_STOPWATCH,
  ANN_ELEMENT_VIBRA,
  ANN_ELEMENT_MAX
}AnnElementIdT;

#define  ANN_ELEMENT_MESSAGE   ANN_ELEMENT_MESSAGE_GENERAL
#define ANN_ELEMENT_RSSI  ANN_ELEMENT_LONGRSSI
#define ANN_ELEMENT_USB   ANN_ELEMENT_USB_CABLE

typedef enum
{
  ANN_PRI_0 = 0,
  ANN_PRI_1,
  ANN_PRI_2,
  ANN_PRI_3,
  ANN_PRI_4,
  ANN_PRI_5,
  ANN_PRI_6,
  ANN_PRI_7,
  ANN_PRI_8,
  ANN_PRI_9,
  ANN_PRI_10,
  ANN_PRI_11,
  ANN_PRI_12,
  ANN_PRI_13,
  ANN_PRI_14,
  ANN_PRI_15,
  ANN_PRI_16,
  ANN_PRI_17,
  ANN_PRI_18,
  ANN_PRI_19,
  ANN_PRI_20,
  ANN_PRI_MAX
}AnnPriorityT;

AnnPriorityT GetElementPRI(AnnElementIdT ElementId);
AnnStateIdT GetElementBlankState(AnnElementIdT ElementId);
AnnElementIdT GetElementIdByState(AnnStateIdT StateId);
bool IsBatteryLevel(AnnStateIdT StateId);
ResourceIdT GetAnnResourceBySystemState(SysStateIdT sysStateId);


#endif

