

#ifndef UIMAILMSGIDS_H
#define UIMAILMSGIDS_H 
/******************************************************************************
* 
*
******************************************************************************/
#include "buidefs.h"
#include "buimsgdefs.h"
#include "buiappids.h"

enum
{
  KEYMSG_PRESS = (MAIL_CAT(KEY_CAT) | (0 & ID_MASK)),
  KEYMSG_HOLD,
  KEYMSG_RELEASE,

  ACCMSG_CONNECT = (MAIL_CAT(ACCESSORY_CAT) | (0 & ID_MASK)),
  ACCMSG_REMOVE,
  ACCMSG_BATTERY_LEVEL_CHANGE,
  ACCMSG_BATTERY_STATUS_CHANGE,  

  WINMSG_CREATE = (MAIL_CAT(WINDOW_CAT) | (0 & ID_MASK)),
  WINMSG_DESTROY,
  WINMSG_MOVE,
  WINMSG_SIZE,
  WINMSG_ENABLE,
  WINMSG_SHOW,
  WINMSG_SETFOCUS,
  WINMSG_KILLFOCUS,
  WINMSG_CHANGEFOCUS,
  WINMSG_SHOWNOTIFY,
  WINMSG_HIDENOTIFY,
  WINMSG_PARENTNOTIFY,
  WINMSG_NOTIFY,
  WINMSG_ERASEBKGND,
  WINMSG_PAINT,
  WINMSG_KEYPRESS,
  WINMSG_KEYHOLD,
  WINMSG_KEYRELEASE,

  //For WinManager
  WINMSG_ADD_DIALOG,
  WINMSG_REMOVE_DIALOG,
  WINMSG_HIDE_DIALOG,
  WINMSG_RAISE_DIALOG,

  //For Popup
  WINMSG_CLOSE_POPUP,
  //For HelpText
  WINMSG_HELPTEXT_TIMEOUT,
  WINMSG_CLOSE_HELPTEXT,
  //WINMSG_HELPTEXT_CLOSED,

  WINMSG_CLOSE_POPUPEX,
  //For SoftKeyBarCtrl
  WINMSG_SOFT_SELECT_KEY,
  WINMSG_SOFT_CLEAR_KEY,

  WINMSG_APP_NOTIFY_EVENT,

  //For DateTimeCtrl
  WINMSG_CLOCK_ACT,
  WINMSG_DATE_HOLD_KEY,
  //For MenuCtrl
  WINMSG_MENU_TEXT_ANIMATION,/*menudrawer handle the message*/
  WINMSG_MENU_ITEM_HOVERED,/*menu setting dialog handle the message*/
  WINMSG_MENU_HOLD_KEY,/*Menu control handle the message*/
  WINMSG_MENU_CHECKBOX_CHANGE_STATUS,
  WINMSG_MENU_CHECKBOX_CHECK_ALL,
  WINMSG_MENU_CHECKBOX_UNCHECK_ALL,
  WINMSG_MENU_ITEM_SCROLL,//Add by BYD before Scroll Item,Param will be next(1) or prev(0)
  WINMSG_MENU_ITEM_SELECTED,
  
  //For EditCtrl
  WINMSG_EDIT_NORMALHANDLE_BEGIN,
  WINMSG_EDIT_CLEAR_ALL,
  WINMSG_CARET_BLINK,
  WINMSG_EDIT_NORMALHANDLE_END,
  
  WINMSG_EDIT_PARAMHANDLE_BEGIN,
  WINMSG_EDIT_INSERT_SYMBOL,
  WINMSG_EDIT_INSERT_SMILEY,
  WINMSG_EDIT_INSERT_CHARACTER,
  WINMSG_EDIT_MARKTEXT,
  WINMSG_EDIT_MARKALL,
  WINMSG_EDIT_PASTE,
  WINMSG_EDIT_CUTMARKED,
  WINMSG_EDIT_EXITMARKING,
  WINMSG_EDIT_WRITINGLANGUAGESETTING,
  WINMSG_EDIT_WRITINGLANGUAGE_SELECTED,
  WINMSG_EDIT_PREDICTIONOPTIONS,
  WINMSG_EDIT_PREDICTION,
  WINMSG_EDIT_PREDICTIONON,
  WINMSG_EDIT_PREDICTIONOFF,
  WINMSG_EDIT_PREDICTIONTYPE,
  WINMSG_EDIT_PREDICTIONNORMAL,
  WINMSG_EDIT_PREDICTIONWORDSUGG,
  WINMSG_EDIT_MATCHES,
  WINMSG_EDIT_MATCHES_SELECTED,
  WINMSG_EDIT_INSERTWORD,
  WINMSG_EDIT_EDITWORD,
  WINMSG_EDIT_SAVEWORD,
  WINMSG_EDIT_ACTIVEPREDICTION_QUERY,
  WINMSG_EDIT_EDITORSETTING,
  WINMSG_EDIT_NUMBERMODE,
  WINMSG_EDIT_PARAMHANDLE_END,
  WINMSG_EDIT_FOCUSHANDLE_BEGIN,

  WINMSG_EDIT_FOCUSHANDLE_END,
  WINMSG_EDIT_IME_CLOSE,

  //For StaticTextCtrl  
  WINMSG_STATIC_TEXT_TIMER,

  //For SettingDialog
  WINMSG_SETTING_OPEN_DIALOG,
  WINMSG_SETTING_CANCEL_DIALOG,
  WINMSG_SETTING_SELECT_OPTION,
  WINMSG_SETTING_SAVE_EDIT,
  WINMSG_SETTING_NEXT_EDIT,

  //For announciator
  WINMSG_ANN_ANIMATION_NOTIFY,

  //For AnimationCtrl
  WINMSG_ANIMATION_TIMER,

  //For DateCtrl
  WINMSG_DATE_TIMER,

  //For ComboBoxControlC
  WINMSG_COMBOBOX_BACKSPACE,
  WINMSG_COMBOBOX_SELECTITEM,
  WINMSG_COMBOBOX_TEST1,
  
  //For TitleBarCtrl
  WINMSG_TITLEBAR_BATCHG,
  WINMSG_TITLEBAR_BATBEGN,
  WINMSG_TITLEBAR_BATSTOP,
  WINMSG_TITLEBAR_SGNCHG,
  WINMSG_TITLEBAR_LCLTIME,
  WINMSG_TITLEBAR_INDTIME,
  WINMSG_TITLEBAR_ELECTRICIZETIME,
  WINMSG_TITLEBAR_INDTIMESTOP,
  //For CheckboxCtrl
  WINMSG_CHECKBOX_CHECKED,
  WINMSG_CHECKBOX_UNCHECKED,
  
  ANNMSG_STATE_NOTIFY = (MAIL_CAT(ANNOUNCIATOR_CAT) | (0 & ID_MASK)),

  APPMSG_START = APPCAT(APPID_NONE,1),
  APPMSG_SUSPEND,
  APPMSG_RESUME,
  APPMSG_STOP,
  APPMSG_POPUP_OPTIONS,
  APPMSG_SET_VALUE,
  APPMSG_SOUND_EVENT,
  APPMSG_EARPHONE_EVENT,
  APPMSG_STORAGE_EVENT,
  APPMSG_CONFLICT_EVENT,
  APPMSG_TURNON_LIGHT_EVENT,//turn on LCD & KEYPAD

  //For Scheduler
  SCHMSG_PREPARE_ALL_APPT = (MAIL_CAT(SCHEDULER_CAT) | (0 & ID_MASK)),
  SCHMSG_AWAKE_ALL_APPT,
  SCHMSG_ALERT_APPT,

  //For file
  FILMSG_LIST_FILES = (MAIL_CAT(FILE_CAT) | (0 & ID_MASK)),
  FILMSG_LIST_FILES_OVER,
  FILMSG_READ_FILE,
  FILMSG_READ_FILE_OVER,
  FILMSG_WRITE_FILE,
  FILMSG_WRITE_FILE_OVER,
  FILMSG_DELETE_FILES,
  FILMSG_DELETE_FILES_OVER,
  FILMSG_DELETE_DIR,
  FILMSG_DELETE_DIR_OVER,
  FILMSG_MOVE_FILES,
  FILMSG_MOVE_FILES_OVER,
  FILMSG_MOVE_DIR,
  FILMSG_MOVE_DIR_OVER,
//for timer
  TIMER_TIMEOUT = (MAIL_CAT(TIMER_CAT) | (0 & ID_MASK))
};




#endif

