#ifndef UISYSTEMFILEDEF_H_
#define UISYSTEMFILEDEF_H_

#include "aslmididef.h"
#include "balfsicfg.h"

#define MAX_FILE_NAME_LENGTH  256  //!< the max length of Filename
#define MAX_SUFFIX_NAME_LENGTH  5  //!< the max length of Filename

//! File path seperator
#ifdef BYD_USE_SIM
#define FILE_PATH_SEPARATOR "\\"
#define FILE_PATH_SEPARATOR_CHAR '\\'
#define FILE_PATH_BLANK ""
#else
#define FILE_PATH_SEPARATOR "/"
#define FILE_PATH_SEPARATOR_CHAR '/'
#define FILE_PATH_BLANK " "
#endif

#define FILE_NAME_DOT '.'

//////
#ifdef BYD_USE_SIM
#define UserRootDir "\\user"
#else
#define UserRootDir DFS2_VOLUME_NAME
#endif

//! The path to store music files in coyote
#define RESERVED_PATH_IMAGES      UserRootDir FILE_PATH_SEPARATOR "Images"
#define RESERVED_PATH_MUSIC       UserRootDir FILE_PATH_SEPARATOR "Music"FILE_PATH_BLANK"files"
#define RESERVED_PATH_THEMES      UserRootDir FILE_PATH_SEPARATOR "Themes"
#define RESERVED_PATH_GRAPHICS    UserRootDir FILE_PATH_SEPARATOR "Graphics"
#define RESERVED_PATH_TONES       UserRootDir FILE_PATH_SEPARATOR "Tones"
#define RESERVED_PATH_RECORDINGS  UserRootDir FILE_PATH_SEPARATOR "Recordings"
#define RESERVED_PATH_RECEIVED    UserRootDir FILE_PATH_SEPARATOR "Received"FILE_PATH_BLANK"files"

#define RESERVED_PATH_WALLPAPERS  RESERVED_PATH_GRAPHICS FILE_PATH_SEPARATOR "Wallpapers"
#define RESERVED_PATH_SCRSAVERS   RESERVED_PATH_GRAPHICS FILE_PATH_SEPARATOR "Screen"FILE_PATH_BLANK"savers"
#define RESERVED_PATH_CLIPARTS    RESERVED_PATH_GRAPHICS FILE_PATH_SEPARATOR "Clip-arts"
#define RESERVED_PATH_FRAMES      RESERVED_PATH_GRAPHICS FILE_PATH_SEPARATOR "Frames"

#define RESERVED_PATH_RINGTONES   RESERVED_PATH_TONES FILE_PATH_SEPARATOR "Ringing"FILE_PATH_BLANK"tones"
#define RESERVED_PATH_ALERTTONES  RESERVED_PATH_TONES FILE_PATH_SEPARATOR "Alert"FILE_PATH_BLANK"tones"


#define SYS_PATH_NAME_LENGTH 64
typedef struct
{
  char PathName[SYS_PATH_NAME_LENGTH];
  uint8 FileIndex;
}UiSysFileT;

#define SYS_FILE_NAME_0  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Agency.mid"
#define SYS_FILE_NAME_1  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Aires.mid"
#define SYS_FILE_NAME_2  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Ballroom.mid"
#define SYS_FILE_NAME_3  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Brook.mid"
#define SYS_FILE_NAME_4  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Dance floor.mid"
#define SYS_FILE_NAME_5  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Desk phone.mid"
#define SYS_FILE_NAME_6  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Dreamy rainy day.mid"
#define SYS_FILE_NAME_7  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Fly high.mid"
#define SYS_FILE_NAME_8  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Hot swing.mid"
#define SYS_FILE_NAME_9  RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Luminosity.mid"
#define SYS_FILE_NAME_10 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Masquerade.mid"
#define SYS_FILE_NAME_11 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "More mambo.mid"
#define SYS_FILE_NAME_12 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Nocturnal.mid"
#define SYS_FILE_NAME_13 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Nokia tune.mid"
#define SYS_FILE_NAME_14 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "One two three.mid"
#define SYS_FILE_NAME_15 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Party.mid"
#define SYS_FILE_NAME_16 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Patten.mid"
#define SYS_FILE_NAME_17 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Polite.mid"
#define SYS_FILE_NAME_18 RESERVED_PATH_RINGTONES FILE_PATH_SEPARATOR "Timid.mid"
#define SYS_FILE_NAME_19 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Calendar 1.mid"
#define SYS_FILE_NAME_20 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Calendar 2.mid"
#define SYS_FILE_NAME_21 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Calendar 3.mid"
#define SYS_FILE_NAME_22 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Clock 1.mid"
#define SYS_FILE_NAME_23 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Clock 2.mid"
#define SYS_FILE_NAME_24 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Clock 3.mid"
#define SYS_FILE_NAME_25 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Message 1.mid"
#define SYS_FILE_NAME_26 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Message 2.mid"
#define SYS_FILE_NAME_27 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Message 3.mid"
#define SYS_FILE_NAME_28 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Message 4.mid"
#define SYS_FILE_NAME_29 RESERVED_PATH_ALERTTONES FILE_PATH_SEPARATOR "Message 5.mid"

const static UiSysFileT UiSysFile[] = {
  {SYS_FILE_NAME_0,   E_RINGTONE_AGENCY},           
  {SYS_FILE_NAME_1,   E_RINGTONE_AIRES},            
  {SYS_FILE_NAME_2,   E_RINGTONE_BALLROOM},            
  {SYS_FILE_NAME_3,   E_RINGTONE_BROOK},            
  {SYS_FILE_NAME_4,   E_RINGTONE_DANCE_FLOOR},      
  {SYS_FILE_NAME_5,   E_RINGTONE_DESK_PHONE},       
  {SYS_FILE_NAME_6,   E_RINGTONE_GREAMY_RAINY_DAY}, 
  {SYS_FILE_NAME_7,   E_RINGTONE_FLY_HIGH},         
  {SYS_FILE_NAME_8,   E_RINGTONE_HOT_SWING},        
  {SYS_FILE_NAME_9,   E_RINGTONE_LUMINOSITY},       
  {SYS_FILE_NAME_10,  E_RINGTONE_MASQUERADE},       
  {SYS_FILE_NAME_11,  E_RINGTONE_MORE_MAMBO},       
  {SYS_FILE_NAME_12,  E_RINGTONE_NOCTURNAL},        
  {SYS_FILE_NAME_13,  E_RINGTONE_NOKIA_TUNE},       
  {SYS_FILE_NAME_14,  E_RINGTONE_ONE_TWO_THREE},    
  {SYS_FILE_NAME_15,  E_RINGTONE_PARTY},            
  {SYS_FILE_NAME_16,  E_RINGTONE_PATTERN},          
  {SYS_FILE_NAME_17,  E_RINGTONE_TIMID},            
  {SYS_FILE_NAME_18,  E_RINGTONE_AGENCY},           
  {SYS_FILE_NAME_19,  E_ALERTTONE_CALENDAR1},       
  {SYS_FILE_NAME_20,  E_ALERTTONE_CALENDAR2},       
  {SYS_FILE_NAME_21,  E_ALERTTONE_CALENDAR3},       
  {SYS_FILE_NAME_22,  E_ALERTTONE_CLOCK1},          
  {SYS_FILE_NAME_23,  E_ALERTTONE_CLOCK2},          
  {SYS_FILE_NAME_24,  E_ALERTTONE_CLOCK3},          
  {SYS_FILE_NAME_25,  E_ALERTTONE_MESSAGE1},        
  {SYS_FILE_NAME_26,  E_ALERTTONE_MESSAGE2},        
  {SYS_FILE_NAME_27,  E_ALERTTONE_MESSAGE3},        
  {SYS_FILE_NAME_28,  E_ALERTTONE_MESSAGE4},        
  {SYS_FILE_NAME_29,  E_ALERTTONE_MESSAGE5}       
};

#endif
