#ifndef __RV_SWE_H__
#define __RV_SWE_H__
#define RVM_AS_SWE
#define RVM_AUDIO_SWE
#define RVM_BAE_SWE
#define RVM_DAR_SWE
#define RVM_DATALIGHT_SWE
#define RVM_DIE_SWE
#define RVM_DIO_IL_SWE
#define RVM_DMA_SWE
#define RVM_ETM_SWE
#define RVM_FFS_SWE
#define RVM_GBI_SWE
#define RVM_GIL_SWE
#define RVM_HASH_SWE
#define RVM_IMG_SWE
#define RVM_JPEGCODEC_SWE
#define RVM_KPD_SWE
#define RVM_LCC_SWE
#define RVM_LCD_SWE
#define RVM_LLS_SWE
#define RVM_MKS_SWE
#define RVM_MPK_SWE
//#define RVM_MSL_SWE
//#define RVM_OMX_CORE_SWE
//#define RVM_OMX_IMG_SWE
//#define RVM_OMX_SSL_SWE
#define RVM_RFSFAT_SWE
#define RVM_RFS_SWE
#define RVM_RNG_SWE
#define RVM_RTC_SWE
#define RVM_SECURE_ROM_SWE
//#define RVM_SSL_SWE
#define RVM_TTY_SWE
#define RVM_UICC_SWE
#define RVM_USBFAX_SWE
#define RVM_USB_SWE

#endif /* __RV_SWE_H__ */
